name: FromDoppler

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main", "INT"]
    tags:
      - v*.*.*

jobs:
  dotnet:
    name: Continuous Integration
    uses: FromDoppler/.github/.github/workflows/dotnet.yml@main
    secrets: inherit
  nuget:
    if: ${{ github.event_name == 'push' }}
    name: Continuous Delivery
    uses: FromDoppler/.github/.github/workflows/continuous-delivery-nuget.yml@main
    secrets: inherit
