using GreenArrow.Engine.Model.Events;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace GreenArrow.Engine.EventNotificationSystem
{
    /// <summary>
    /// /Controller to receive events generated by Green Arrow Event Notification System
    /// </summary>
    [Route("api/[controller]")]
    [ApiController]
    public sealed class GreenArrowEventController : ControllerBase
    {
        private readonly ILogger<GreenArrowEventController> _logger;
        private readonly IEventReceptor _eventReceptor;

        /// <summary>
        /// Create an instance of GreenArrowEventController
        /// </summary>
        public GreenArrowEventController(
            ILogger<GreenArrowEventController> logger,
            IEventReceptor eventReceptor
            )
        {
            _logger = logger;
            _eventReceptor = eventReceptor;
        }

        /// <summary>
        /// Receive Bounce All events
        /// </summary>
        [Route(nameof(EventType.BounceAll))]
        [HttpPost()]
        public async Task<IActionResult> PostBounceAll([FromBody] List<BounceAll> events)
        {
            _logger.LogDebug("Green Arrow {GreenArrowEventType} events received", EventType.BounceAll);

            foreach (var bounceAll in events)
            {
                await _eventReceptor.HandleAsync(bounceAll);
            }

            _logger.LogDebug("Green Arrow {GreenArrowEventType} events handled", EventType.BounceAll);

            return Ok();
        }

        /// <summary>
        /// Receive Bounce Bad Address events
        /// </summary>
        [Route(nameof(EventType.BounceBadAddress))]
        [HttpPost()]
        public async Task<IActionResult> PostBounceBadAddress([FromBody] List<BounceBadAddress> events)
        {
            _logger.LogDebug("Green Arrow {GreenArrowEventType} events received", EventType.BounceBadAddress);

            foreach (var bounceBadAddress in events)
            {
                await _eventReceptor.HandleAsync(bounceBadAddress);
            }

            _logger.LogDebug("Green Arrow {GreenArrowEventType} events handled", EventType.BounceBadAddress);

            return Ok();
        }

        /// <summary>
        /// Receive Delivery Attempt events
        /// </summary>
        [Route(nameof(EventType.DeliveryAttempt))]
        [HttpPost()]
        public async Task<IActionResult> PostDeliveryAttempt([FromBody] List<DeliveryAttempt> events)
        {
            _logger.LogDebug("Green Arrow {GreenArrowEventType} events received", EventType.DeliveryAttempt);

            foreach (var deliveryAttempt in events)
            {
                await _eventReceptor.HandleAsync(deliveryAttempt);
            }

            _logger.LogDebug("Green Arrow {GreenArrowEventType} events handled", EventType.DeliveryAttempt);

            return Ok();
        }

        /// <summary>
        /// Receive Click Tracking events
        /// </summary>
        [Route(nameof(EventType.EngineClick))]
        [HttpPost()]
        public async Task<IActionResult> PostClickTracking([FromBody] List<ClickTracking> events)
        {
            _logger.LogDebug("Green Arrow {GreenArrowEventType} events received", EventType.EngineClick);

            foreach (var deliveryAttempt in events)
            {
                await _eventReceptor.HandleAsync(deliveryAttempt);
            }

            _logger.LogDebug("Green Arrow {GreenArrowEventType} events handled", EventType.EngineClick);

            return Ok();
        }

        /// <summary>
        /// Receive Open Tracking events
        /// </summary>
        [Route(nameof(EventType.EngineOpen))]
        [HttpPost()]
        public async Task<IActionResult> PostOpenTracking([FromBody] List<OpenTracking> events)
        {
            _logger.LogDebug("Green Arrow {GreenArrowEventType} events received", EventType.EngineOpen);

            foreach (var openTracking in events)
            {
                await _eventReceptor.HandleAsync(openTracking);
            }

            _logger.LogDebug("Green Arrow {GreenArrowEventType} events handled", EventType.EngineOpen);

            return Ok();
        }

        /// <summary>
        /// Receive Spam Compaint events
        /// </summary>
        [Route(nameof(EventType.Scomp))]
        [HttpPost()]
        public async Task<IActionResult> PostSpamComplaint([FromBody] List<SpamComplaint> events)
        {
            _logger.LogDebug("Green Arrow {GreenArrowEventType} events received", EventType.Scomp);

            foreach (var spamComplaint in events)
            {
                await _eventReceptor.HandleAsync(spamComplaint);
            }

            _logger.LogDebug("Green Arrow {GreenArrowEventType} events handled", EventType.Scomp);

            return Ok();
        }

        /// <summary>
        /// Receive Unsubscribe events
        /// </summary>
        [Route(nameof(EventType.EngineUnsub))]
        [HttpPost()]
        public async Task<IActionResult> PostUnsubscribe([FromBody] List<Unsubscribe> events)
        {
            _logger.LogDebug("Green Arrow {GreenArrowEventType} events received", EventType.EngineUnsub);

            foreach (var unsubscribe in events)
            {
                await _eventReceptor.HandleAsync(unsubscribe);
            }

            _logger.LogDebug("Green Arrow {GreenArrowEventType} events handled", EventType.EngineUnsub);

            return Ok();
        }
    }
}
